services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://niteshport:nitesh9631@portfolio.ighmbje.mongodb.net/?appName=portfolio"
      - key: JWT_SECRET
        value: "super_secret_key_change_this_for_production_jwt"
      - key: PORT
        value: "5000"
    healthCheckPath: /health
